openapi: 3.2.0
info:
  title: AgentCheckup Tiers API
  version: 0.1.0
tags:
- name: Tiers
paths:
  /api/tiers:
    get:
      summary: Get Tiers
      operationId: get_tiers_api_tiers_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Tiers
